apiVersion: v1
kind: ConfigMap
metadata:
  name: ksh-chart-{{ .Release.Name }}-configmap
  namespace:  {{ .Values.testNamespace }}
data:
  myvalue: "Hello World"
  valueAssign: {{ .Values.testValues }}
